<?php

require_once __DIR__ . '/../vendor/fpdf/fpdf.php';

class AuditLogPdf extends FPDF {
    private $logoPath;
    private $generatedBy;
    private $printedAt;

    public function __construct($logoPath, $generatedBy) {
        parent::__construct('P', 'mm', 'A4');
        $this->logoPath = $logoPath;
        $this->generatedBy = $generatedBy;
        $this->printedAt = date('F d, Y h:i A');
        $this->SetMargins(12, 12, 12);
        $this->SetAutoPageBreak(true, 18);
        $this->AliasNbPages();
        $this->SetTitle('SICMS Audit Logs');
        $this->SetAuthor($generatedBy);
    }

    public function Header() {
        if (is_file($this->logoPath)) {
            $this->Image($this->logoPath, 12, 9, 20, 20);
        }

        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 12);
        $this->Cell(0, 5, 'CENTRAL LUZON STATE UNIVERSITY', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Student Discipline and Reformation Unit (SDRU)', 0, 1, 'C');
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 5, 'Discipline and Reformation Information Unit (DARIS)', 0, 1, 'C');
        $this->SetDrawColor(26, 157, 0);
        $this->SetLineWidth(0.6);
        $this->Line(12, 30, 198, 30);
        $this->Ln(6);
    }

    public function Footer() {
        $this->SetY(-12);
        $this->SetDrawColor(190, 205, 187);
        $this->Line(12, $this->GetY(), 198, $this->GetY());
        $this->SetFont('Helvetica', '', 7.5);
        $this->SetTextColor(83, 96, 82);
        $this->Cell(100, 7, 'Generated by SICMS | Printed ' . $this->printedAt, 0, 0, 'L');
        $this->Cell(0, 7, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }

    public function reportHeading(array $filters) {
        $this->SetTextColor(23, 32, 23);
        $this->SetFont('Helvetica', 'B', 14);
        $this->Cell(0, 8, 'AUDIT LOGS', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Generated by: ' . $this->clean($this->generatedBy) . '  |  Generated: ' . $this->printedAt, 0, 1, 'C');
        $this->Ln(3);

        $hasFilters = false;
        foreach (['search', 'account_id', 'role', 'action', 'date_from', 'date_to'] as $key) {
            if (!empty($filters[$key])) {
                $hasFilters = true;
                break;
            }
        }

        if ($hasFilters) {
            $this->sectionTitle('Applied Filters');
            $this->SetTextColor(23, 32, 23);
            $this->SetFont('Helvetica', '', 8.5);
            $rows = [
                [($filters['search'] !== '' ? 'Search: ' . $filters['search'] : '-'), ($filters['role'] !== '' ? 'Role: ' . $filters['role'] : '-')],
                [($filters['action'] !== '' ? 'Action: ' . $filters['action'] : '-'), ($filters['date_from'] !== '' ? 'From: ' . $filters['date_from'] : '-')],
                [($filters['account_id'] ? 'User ID: ' . $filters['account_id'] : '-'), ($filters['date_to'] !== '' ? 'To: ' . $filters['date_to'] : '-')],
            ];

            foreach ($rows as $row) {
                $this->Cell(91, 6, $this->clean($row[0]), 1, 0, 'L');
                $this->Cell(91, 6, $this->clean($row[1]), 1, 0, 'L');
                $this->Ln();
            }

            $this->Ln(3);
        }
    }

    public function sectionTitle($title) {
        $this->SetFillColor(234, 247, 232);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 9);
        $this->Cell(0, 6, $title, 0, 1, 'L', true);
        $this->SetTextColor(23, 32, 23);
    }

    public function tableHeader() {
        $this->SetFillColor(18, 60, 27);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 7.5);

        $headers = ['#', 'Date & Time', 'User', 'Role', 'Action', 'Description', 'IP Address'];
        $widths = $this->colWidths();

        foreach ($headers as $i => $header) {
            $this->Cell($widths[$i], 7, $header, 1, 0, 'C', true);
        }

        $this->Ln();
        $this->SetTextColor(23, 32, 23);
    }

    public function tableRow(int $rowNumber, array $row) {
        $widths = $this->colWidths();
        $values = [
            (string) $rowNumber,
            $this->formatDateTime($row['created_at'] ?? ''),
            $row['user_name'] ?? '',
            $row['user_role'] ?? '',
            $row['action'] ?? '',
            $row['description'] ?? '',
            $row['ip_address'] ?? '',
        ];

        $cleanValues = array_map([$this, 'clean'], $values);

        $lineCounts = [];
        foreach ($cleanValues as $i => $text) {
            $lineCounts[] = $this->lineCount($widths[$i], $text);
        }

        $height = max(1, max($lineCounts)) * 4.5;
        $height = max($height, 6);

        if ($this->GetY() + $height > 272) {
            $this->AddPage();
            $this->tableHeader();
        }

        $fill = $rowNumber % 2 === 0;
        $this->SetFillColor(247, 250, 246);

        $x = $this->GetX();
        $y = $this->GetY();

        foreach ($cleanValues as $i => $text) {
            $width = $widths[$i];
            $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
            $this->SetXY($x + 1, $y + 1);
            $align = $i === 0 ? 'C' : ($i === 6 ? 'R' : 'L');
            $this->MultiCell($width - 2, 4.5, $text, 0, $align);
            $x += $width;
        }

        $this->SetXY(12, $y + $height);
    }

    public function recordCount(int $total) {
        $this->SetFont('Helvetica', '', 8);
        $this->SetTextColor(83, 96, 82);
        $this->Cell(0, 5, 'Total records: ' . number_format($total), 0, 1, 'R');
        $this->SetTextColor(23, 32, 23);
    }

    private function colWidths() {
        return [10, 32, 30, 22, 30, 44, 18];
    }

    private function formatDateTime($value) {
        $ts = strtotime($value);
        return $ts ? date('Y-m-d H:i', $ts) : (string) $value;
    }

    private function clean($value) {
        return iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', (string) $value);
    }

    private function lineCount($width, $text) {
        $words = preg_split('/\s+/', trim($text));
        $lines = 1;
        $current = '';

        foreach ($words as $word) {
            $candidate = $current === '' ? $word : $current . ' ' . $word;
            if ($this->GetStringWidth($candidate) > $width - 2) {
                $lines++;
                $current = $word;
            } else {
                $current = $candidate;
            }
        }

        return $lines;
    }
}
