<?php

require_once __DIR__ . '/../vendor/fpdf/fpdf.php';

class AuditLogPdf extends FPDF {
    private $logoPath;
    private $generatedBy;
    private $printedAt;
    private $rowIndex = 0;
    private $widths = [];
    private $headers = [];
    private $columnKeys = [];

    private static $allowedColumns = [
        'created_at' => ['label' => 'Date & Time', 'weight' => 1.2],
        'user_name' => ['label' => 'User', 'weight' => 1.3],
        'user_role' => ['label' => 'Role', 'weight' => 1.0],
        'action' => ['label' => 'Action / Activity', 'weight' => 1.2],
        'description' => ['label' => 'Description / Details', 'weight' => 2.4],
        'ip_address' => ['label' => 'IP Address', 'weight' => 1.0],
        'user_agent' => ['label' => 'Browser / Device', 'weight' => 1.8],
    ];

    public function __construct($logoPath, $generatedBy, array $selectedColumns = []) {
        parent::__construct('L', 'mm', 'A4');
        $this->logoPath = $logoPath;
        $this->generatedBy = $generatedBy;
        $this->printedAt = date('F d, Y h:i A');
        $this->SetMargins(12, 12, 12);
        $this->SetAutoPageBreak(true, 18);
        $this->AliasNbPages();
        $this->SetTitle('DARIS Audit Log Report');
        $this->SetAuthor($generatedBy);

        $this->configureColumns($selectedColumns);
    }

    private function configureColumns(array $selectedColumns) {
        $validKeys = [];
        foreach ($selectedColumns as $col) {
            if (isset(self::$allowedColumns[$col])) {
                $validKeys[] = $col;
            }
        }
        if (empty($validKeys)) {
            $validKeys = array_keys(self::$allowedColumns);
        }

        $this->columnKeys = $validKeys;
        $totalWeight = 0;
        foreach ($validKeys as $key) {
            $totalWeight += self::$allowedColumns[$key]['weight'];
            $this->headers[] = self::$allowedColumns[$key]['label'];
        }

        $usableWidth = 273; // 297 - 24
        foreach ($validKeys as $key) {
            $weight = self::$allowedColumns[$key]['weight'];
            $this->widths[] = $usableWidth * ($weight / $totalWeight);
        }
    }

    public function Header() {
        if (is_file($this->logoPath)) {
            $this->Image($this->logoPath, 12, 9, 20, 20);
        }

        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 12);
        $this->Cell(0, 5, 'CENTRAL LUZON STATE UNIVERSITY', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Student Discipline and Reformation Unit (SDRU)', 0, 1, 'C');
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 5, 'Discipline and Reformation Information System (DARIS)', 0, 1, 'C');
        $this->SetDrawColor(26, 157, 0);
        $this->SetLineWidth(0.6);
        $this->Line(12, 30, 285, 30);
        $this->Ln(6);
    }

    public function Footer() {
        $this->SetY(-12);
        $this->SetDrawColor(190, 205, 187);
        $this->Line(12, $this->GetY(), 285, $this->GetY());
        $this->SetFont('Helvetica', '', 7.5);
        $this->SetTextColor(83, 96, 82);
        $this->Cell(130, 7, 'This document was electronically generated by DARIS. | Printed ' . $this->printedAt, 0, 0, 'L');
        $this->Cell(0, 7, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }

    public function reportHeading(array $filters) {
        $this->SetTextColor(23, 32, 23);
        $this->SetFont('Helvetica', 'B', 16);
        $this->Cell(0, 8, 'AUDIT LOG REPORT', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Generated by: ' . $this->clean($this->generatedBy) . '  |  Generated: ' . $this->printedAt, 0, 1, 'C');
        $this->Ln(3);

        $filterTexts = [];
        if (!empty($filters['search'])) {
            $filterTexts['Search Term'] = $filters['search'];
        }
        if (!empty($filters['account_id'])) {
            $filterTexts['User Account ID'] = $filters['account_id'];
        }
        if (!empty($filters['role'])) {
            $filterTexts['User Role'] = $filters['role'];
        }
        if (!empty($filters['action'])) {
            $filterTexts['Action'] = $filters['action'];
        }
        if (!empty($filters['date_from'])) {
            $filterTexts['Date From'] = $filters['date_from'];
        }
        if (!empty($filters['date_to'])) {
            $filterTexts['Date To'] = $filters['date_to'];
        }

        if (!empty($filterTexts)) {
            $this->sectionTitle('Applied Filters');
            $this->SetFont('Helvetica', '', 8.5);
            $chunks = array_chunk($filterTexts, 3, true);
            foreach ($chunks as $chunk) {
                $width = 273 / count($chunk);
                foreach ($chunk as $label => $value) {
                    $this->Cell($width, 6, $this->clean($label . ': ' . $value), 1, 0, 'L');
                }
                $this->Ln();
            }
            $this->Ln(3);
        }
    }

    public function sectionTitle($title) {
        $this->SetFillColor(234, 247, 232);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 9.5);
        $this->Cell(0, 6, $title, 0, 1, 'L', true);
        $this->SetTextColor(23, 32, 23);
    }

    public function tableHeader() {
        $this->SetFillColor(18, 60, 27);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 8);

        foreach ($this->headers as $i => $header) {
            $this->Cell($this->widths[$i], 7.5, $header, 1, 0, 'C', true);
        }

        $this->Ln();
        $this->SetTextColor(23, 32, 23);
    }

    public function tableRow(array $row) {
        $values = [];
        foreach ($this->columnKeys as $key) {
            switch ($key) {
                case 'created_at':
                    $values[] = $this->formatDateTime($row['created_at'] ?? '');
                    break;
                case 'user_name':
                    $values[] = $row['user_name'] ?? '';
                    break;
                case 'user_role':
                    $values[] = ucwords(str_replace(['-', '_'], ' ', $row['user_role'] ?? ''));
                    break;
                case 'action':
                    $values[] = $row['action'] ?? '';
                    break;
                case 'description':
                    $values[] = $row['description'] ?? '';
                    break;
                case 'ip_address':
                    $values[] = $row['ip_address'] ?? '';
                    break;
                case 'user_agent':
                    $values[] = $row['user_agent'] ?? '';
                    break;
                default:
                    $values[] = '';
                    break;
            }
        }

        $cleanValues = array_map([$this, 'clean'], $values);
        $lineCounts = [];
        foreach ($cleanValues as $i => $text) {
            $lineCounts[] = $this->lineCount($this->widths[$i], $text);
        }

        $height = max(1, max($lineCounts)) * 5;
        $height = max($height, 6);

        if ($this->GetY() + $height > 185) {
            $this->AddPage();
            $this->sectionTitle('Audit Log Report (continued)');
            $this->tableHeader();
        }

        $fill = $this->rowIndex++ % 2 === 1;
        $this->SetFillColor(247, 250, 246);

        $x = $this->GetX();
        $y = $this->GetY();

        foreach ($cleanValues as $i => $text) {
            $width = $this->widths[$i];
            $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
            $this->SetXY($x + 1, $y + 1);
            $align = ($this->columnKeys[$i] === 'ip_address') ? 'C' : 'L';
            $this->MultiCell($width - 2, 4.5, $text, 0, $align);
            $x += $width;
        }

        $this->SetXY(12, $y + $height);
    }

    public function recordCount(int $total) {
        $this->Ln(2);
        $this->SetFont('Helvetica', 'B', 8.5);
        $this->SetTextColor(18, 60, 27);
        $this->Cell(0, 6, 'Total Exported Records: ' . number_format($total), 0, 1, 'R');
        $this->SetTextColor(23, 32, 23);
    }

    private function formatDateTime($value) {
        $ts = strtotime($value);
        return $ts ? date('Y-m-d H:i', $ts) : (string) $value;
    }

    private function clean($value) {
        return iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', (string) $value);
    }

    private function lineCount($width, $text) {
        $words = preg_split('/\s+/', trim($text));
        $lines = 1;
        $current = '';

        foreach ($words as $word) {
            $candidate = $current === '' ? $word : $current . ' ' . $word;
            if ($this->GetStringWidth($candidate) > $width - 2) {
                $lines++;
                $current = $word;
            } else {
                $current = $candidate;
            }
        }

        return $lines;
    }
}
