<?php

require_once __DIR__ . '/../vendor/fpdf/fpdf.php';

class SicmsReportPdf extends FPDF {
    private $logoPath;
    private $generatedBy;
    private $printedAt;
    private $rowIndex = 0;
    private $widths = [32, 42, 40, 28, 40, 55, 30];

    public function __construct($logoPath, $generatedBy) {
        parent::__construct('L', 'mm', 'A4');
        $this->logoPath = $logoPath;
        $this->generatedBy = $generatedBy;
        $this->printedAt = date('F d, Y h:i A');
        $this->SetMargins(12, 12, 12);
        $this->SetAutoPageBreak(true, 18);
        $this->AliasNbPages();
        $this->SetTitle('SICMS Reports and Dashboard Analytics');
        $this->SetAuthor($generatedBy);
    }

    public function Header() {
        if (is_file($this->logoPath)) $this->Image($this->logoPath, 12, 9, 20, 20);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 12);
        $this->Cell(0, 5, 'CENTRAL LUZON STATE UNIVERSITY', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Student Discipline and Reformation Unit (SDRU)', 0, 1, 'C');
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 5, 'Student Information and Case Management System (SICMS)', 0, 1, 'C');
        $this->SetDrawColor(26, 157, 0);
        $this->SetLineWidth(0.6);
        $this->Line(12, 30, 285, 30);
        $this->Ln(6);
    }

    public function Footer() {
        $this->SetY(-12);
        $this->SetDrawColor(190, 205, 187);
        $this->Line(12, $this->GetY(), 285, $this->GetY());
        $this->SetFont('Helvetica', '', 7.5);
        $this->SetTextColor(83, 96, 82);
        $this->Cell(100, 7, 'Generated by SICMS | Printed ' . $this->printedAt, 0, 0, 'L');
        $this->Cell(0, 7, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }

    public function reportHeading(array $filters) {
        $this->SetTextColor(23, 32, 23);
        $this->SetFont('Helvetica', 'B', 16);
        $this->Cell(0, 8, 'REPORTS AND DASHBOARD ANALYTICS', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Generated by: ' . $this->clean($this->generatedBy) . ' | Generated: ' . $this->printedAt, 0, 1, 'C');
        $this->Ln(3);
        $this->sectionTitle('Applied Filters');
        $this->SetFont('Helvetica', '', 8.5);
        foreach (array_chunk($filters, 4, true) as $chunk) {
            foreach ($chunk as $label => $value) $this->Cell(68, 6, $this->clean($label . ': ' . $value), 1, 0, 'L');
            $this->Ln();
        }
        $this->Ln(3);
    }

    public function executiveSummary(array $summary) {
        $this->sectionTitle('Executive Summary');
        $labels = [
            'total_cases' => 'Total Cases',
            'submitted_cases' => 'Submitted',
            'verified_cases' => 'Verified',
            'returned_for_revision_cases' => 'Returned for Revision',
            'rejected_cases' => 'Rejected',
            'resolved_cases' => 'Resolved',
            'archived_cases' => 'Archived',
            'scheduled_hearings' => 'Scheduled Hearings',
        ];
        foreach (array_chunk($labels, 4, true) as $chunk) {
            foreach ($chunk as $key => $label) {
                $this->SetFillColor(238, 247, 236);
                $this->SetFont('Helvetica', 'B', 8);
                $this->Cell(68, 6, $label, 1, 0, 'C', true);
            }
            $this->Ln();
            foreach ($chunk as $key => $label) {
                $this->SetFont('Helvetica', 'B', 11);
                $this->Cell(68, 8, (string) ($summary[$key] ?? 0), 1, 0, 'C');
            }
            $this->Ln(10);
        }
        $this->SetFont('Helvetica', '', 8.5);
        $this->Cell(136, 6, 'Hearings Today: ' . (int) ($summary['hearings_today'] ?? 0), 1, 0, 'C');
        $this->Cell(136, 6, 'Completed Hearings: ' . (int) ($summary['completed_hearings'] ?? 0), 1, 1, 'C');
        $this->Ln(4);
    }

    public function caseTableHeader() {
        $this->SetFillColor(18, 60, 27);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 8);
        foreach (['Case Number', 'Student Name', 'Classification', 'Status', 'Coordinator', 'College', 'Submitted'] as $index => $heading) {
            $this->Cell($this->widths[$index], 8, $heading, 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(23, 32, 23);
    }

    public function caseRow(array $values) {
        $lineCounts = [];
        foreach ($values as $index => $value) $lineCounts[] = $this->lineCount($this->widths[$index], $this->clean($value));
        $height = max(1, max($lineCounts)) * 5;
        if ($this->GetY() + $height > 190) {
            $this->AddPage();
            $this->sectionTitle('Case Report (continued)');
            $this->caseTableHeader();
        }
        $fill = $this->rowIndex++ % 2 === 1;
        $this->SetFillColor(247, 250, 246);
        $this->SetFont('Helvetica', '', 7.5);
        $x = $this->GetX();
        $y = $this->GetY();
        foreach ($values as $index => $value) {
            $width = $this->widths[$index];
            $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
            $this->SetXY($x + 1, $y + 1);
            $this->MultiCell($width - 2, 4, $this->clean($value), 0, 'L');
            $x += $width;
        }
        $this->SetXY(12, $y + $height);
    }

    public function sectionTitle($title) {
        $this->SetFillColor(234, 247, 232);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 7, $title, 0, 1, 'L', true);
        $this->SetTextColor(23, 32, 23);
    }

    private function clean($value) {
        return iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', (string) $value);
    }

    private function lineCount($width, $text) {
        $words = preg_split('/\s+/', trim($text));
        $lines = 1;
        $current = '';
        foreach ($words as $word) {
            $candidate = $current === '' ? $word : $current . ' ' . $word;
            if ($this->GetStringWidth($candidate) > $width - 2) {
                $lines++;
                $current = $word;
            } else {
                $current = $candidate;
            }
        }
        return $lines;
    }
}
