<?php

require_once __DIR__ . '/../vendor/fpdf/fpdf.php';

class SicmsReportPdf extends FPDF {
    private $logoPath;
    private $generatedBy;
    private $printedAt;
    private $rowIndex = 0;
    private $widths = [32, 36, 20, 36, 24, 40, 49, 30];

    public function __construct($logoPath, $generatedBy) {
        parent::__construct('L', 'mm', 'A4');
        $this->logoPath = $logoPath;
        $this->generatedBy = $generatedBy;
        $this->printedAt = date('F d, Y h:i A');
        $this->SetMargins(12, 12, 12);
        $this->SetAutoPageBreak(true, 18);
        $this->AliasNbPages();
        $this->SetTitle('SICMS Reports and Dashboard Analytics');
        $this->SetAuthor($generatedBy);
    }

    public function Header() {
        if (is_file($this->logoPath)) $this->Image($this->logoPath, 12, 9, 20, 20);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 12);
        $this->Cell(0, 5, 'CENTRAL LUZON STATE UNIVERSITY', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Student Discipline and Reformation Unit (SDRU)', 0, 1, 'C');
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 5, 'Student Information and Case Management System (SICMS)', 0, 1, 'C');
        $this->SetDrawColor(26, 157, 0);
        $this->SetLineWidth(0.6);
        $this->Line(12, 30, 285, 30);
        $this->Ln(6);
    }

    public function Footer() {
        $this->SetY(-12);
        $this->SetDrawColor(190, 205, 187);
        $this->Line(12, $this->GetY(), 285, $this->GetY());
        $this->SetFont('Helvetica', '', 7.5);
        $this->SetTextColor(83, 96, 82);
        $this->Cell(100, 7, 'Generated by SICMS | Printed ' . $this->printedAt, 0, 0, 'L');
        $this->Cell(0, 7, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }

    public function reportHeading(array $filters) {
        $this->SetTextColor(23, 32, 23);
        $this->SetFont('Helvetica', 'B', 16);
        $this->Cell(0, 8, 'REPORTS AND DASHBOARD ANALYTICS', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Generated by: ' . $this->clean($this->generatedBy) . ' | Generated: ' . $this->printedAt, 0, 1, 'C');
        $this->Ln(3);
        $this->sectionTitle('Applied Filters');
        $this->SetFont('Helvetica', '', 8.5);
        foreach (array_chunk($filters, 4, true) as $chunk) {
            foreach ($chunk as $label => $value) $this->Cell(68, 6, $this->clean($label . ': ' . $value), 1, 0, 'L');
            $this->Ln();
        }
        $this->Ln(3);
    }

    public function executiveSummary(array $summary) {
        $this->sectionTitle('Executive Summary');
        $labels = [
            'total_cases' => 'Total Cases',
            'under_investigation_cases' => 'Under Investigation',
            'returned_for_revision_cases' => 'Returned for Revision',
            'rejected_cases' => 'Rejected',
            'resolved_cases' => 'Resolved',
            'escalated_cases' => 'Escalated',
            'archived_cases' => 'Archived',
            'scheduled_hearings' => 'Scheduled Hearings',
        ];
        foreach (array_chunk($labels, 4, true) as $chunk) {
            foreach ($chunk as $key => $label) {
                $this->SetFillColor(238, 247, 236);
                $this->SetFont('Helvetica', 'B', 8);
                $this->Cell(68, 6, $label, 1, 0, 'C', true);
            }
            $this->Ln();
            foreach ($chunk as $key => $label) {
                $this->SetFont('Helvetica', 'B', 11);
                $this->Cell(68, 8, (string) ($summary[$key] ?? 0), 1, 0, 'C');
            }
            $this->Ln(10);
        }
        $this->SetFont('Helvetica', '', 8.5);
        $this->Cell(136, 6, 'Hearings Today: ' . (int) ($summary['hearings_today'] ?? 0), 1, 0, 'C');
        $this->Cell(136, 6, 'Completed Hearings: ' . (int) ($summary['completed_hearings'] ?? 0), 1, 1, 'C');
        $this->Ln(4);
    }

    public function caseTableHeader() {
        $this->SetFillColor(18, 60, 27);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Helvetica', 'B', 8);
        foreach (['Case Number', 'Student Name', 'Gender', 'Classification', 'Status', 'Coordinator', 'College', 'Submitted'] as $index => $heading) {
            $this->Cell($this->widths[$index], 8, $heading, 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(23, 32, 23);
    }

    public function caseRow(array $values) {
        $lineCounts = [];
        foreach ($values as $index => $value) $lineCounts[] = $this->lineCount($this->widths[$index], $this->clean($value));
        $height = max(1, max($lineCounts)) * 5;
        if ($this->GetY() + $height > 190) {
            $this->AddPage();
            $this->sectionTitle('Case Report (continued)');
            $this->caseTableHeader();
        }
        $fill = $this->rowIndex++ % 2 === 1;
        $this->SetFillColor(247, 250, 246);
        $this->SetFont('Helvetica', '', 7.5);
        $x = $this->GetX();
        $y = $this->GetY();
        foreach ($values as $index => $value) {
            $width = $this->widths[$index];
            $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
            $this->SetXY($x + 1, $y + 1);
            $this->MultiCell($width - 2, 4, $this->clean($value), 0, 'L');
            $x += $width;
        }
        $this->SetXY(12, $y + $height);
    }

    public function sectionTitle($title) {
        $this->SetFillColor(234, 247, 232);
        $this->SetTextColor(18, 60, 27);
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 7, $title, 0, 1, 'L', true);
        $this->SetTextColor(23, 32, 23);
    }

    public function yearlyHeading($yearLabel) {
        $this->SetTextColor(23, 32, 23);
        $this->SetFont('Helvetica', 'B', 16);
        $this->Cell(0, 9, 'YEARLY CASES REPORT', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 9);
        $this->Cell(0, 5, 'Year: ' . $this->clean($yearLabel), 0, 1, 'C');
        $this->Cell(0, 5, 'Generated by: ' . $this->clean($this->generatedBy) . ' | Generated: ' . $this->printedAt, 0, 1, 'C');
        $this->Ln(3);
    }

    public function yearlySummaryBlock(array $summary) {
        $this->sectionTitle('1. Summary');
        $labels = [
            'total_cases' => 'Total Cases',
            'pending_cases' => 'Pending',
            'ongoing_cases' => 'Ongoing',
            'under_investigation_cases' => 'Under Investigation',
            'returned_for_revision_cases' => 'Returned for Revision',
            'rejected_cases' => 'Rejected',
            'resolved_cases' => 'Resolved',
            'escalated_cases' => 'Escalated',
            'archived_cases' => 'Archived',
        ];
        $groups = array_chunk($labels, 5, true);
        foreach ($groups as $group) {
            $count = count($group);
            $width = 273 / $count;
            $this->SetFont('Helvetica', 'B', 8);
            foreach ($group as $label) {
                $this->SetFillColor(238, 247, 236);
                $this->Cell($width, 6, $label, 1, 0, 'C', true);
            }
            $this->Ln();
            $this->SetFont('Helvetica', 'B', 11);
            foreach ($group as $key => $label) {
                $this->Cell($width, 8, (string) ($summary[$key] ?? 0), 1, 0, 'C');
            }
            $this->Ln(9);
        }
    }

    public function renderStatsTable(array $columns, array $widths, array $rows, $totalRow = null) {
        $pageBreakY = 195;
        $pageBreakMargin = 3;

        $drawHeader = function () use ($columns, $widths, $pageBreakY, $pageBreakMargin) {
            $texts = array_map([$this, 'clean'], $columns);
            $lineCounts = [];
            foreach ($texts as $index => $text) $lineCounts[] = $this->lineCount($widths[$index], $text);
            $height = max(1, max($lineCounts)) * 6;

            if ($this->GetY() + $height > $pageBreakY - $pageBreakMargin) {
                $this->AddPage();
            }

            $x = $this->GetX();
            $y = $this->GetY();
            $this->SetFillColor(18, 60, 27);
            $this->SetTextColor(255, 255, 255);
            $this->SetFont('Helvetica', 'B', 8);
            foreach ($texts as $index => $text) {
                $width = $widths[$index];
                $this->Rect($x, $y, $width, $height, 'DF');
                $this->SetXY($x + 1, $y + 1);
                $this->MultiCell($width - 2, 4, $text, 0, 'C');
                $x += $width;
            }
            $this->SetXY($this->lMargin, $y + $height);
            $this->SetTextColor(23, 32, 23);
        };

        $drawHeader();

        $rowIndex = 0;
        foreach ($rows as $values) {
            $cleanValues = array_map([$this, 'clean'], $values);
            $lineCounts = [];
            foreach ($cleanValues as $index => $text) $lineCounts[] = $this->lineCount($widths[$index], $text);
            $height = max(1, max($lineCounts)) * 6;

            if ($this->GetY() + $height > $pageBreakY - $pageBreakMargin) {
                $this->AddPage();
                $drawHeader();
            }

            $fill = $rowIndex++ % 2 === 1;
            $x = $this->GetX();
            $y = $this->GetY();
            $this->SetFillColor(247, 250, 246);
            $this->SetFont('Helvetica', '', 8);
            foreach ($cleanValues as $index => $text) {
                $width = $widths[$index];
                $this->Rect($x, $y, $width, $height, $fill ? 'DF' : 'D');
                $this->SetXY($x + 1, $y + 1);
                $this->MultiCell($width - 2, 4, $text, 0, 'L');
                $x += $width;
            }
            $this->SetXY($this->lMargin, $y + $height);
        }

        if ($totalRow !== null) {
            $cleanTotal = array_map([$this, 'clean'], $totalRow);
            $lineCounts = [];
            foreach ($cleanTotal as $index => $text) $lineCounts[] = $this->lineCount($widths[$index], $text);
            $height = max(1, max($lineCounts)) * 6;

            if ($this->GetY() + $height > $pageBreakY - $pageBreakMargin) {
                $this->AddPage();
                $drawHeader();
            }

            $x = $this->GetX();
            $y = $this->GetY();
            $this->SetFillColor(18, 60, 27);
            $this->SetTextColor(255, 255, 255);
            $this->SetFont('Helvetica', 'B', 8);
            foreach ($cleanTotal as $index => $text) {
                $width = $widths[$index];
                $this->Rect($x, $y, $width, $height, 'DF');
                $this->SetXY($x + 1, $y + 1);
                $this->MultiCell($width - 2, 4, $text, 0, 'C');
                $x += $width;
            }
            $this->SetXY($this->lMargin, $y + $height);
            $this->SetTextColor(23, 32, 23);
        }

        $this->Ln(5);
    }

    public function columnWidths($totalColumns, $first = 22, $last = 22) {
        $usable = 273;
        $middleCount = max(0, (int) $totalColumns - 2);

        if ($middleCount === 0) {
            return [$first, max(50, $usable - $first)];
        }

        $middleWidth = ($usable - $first - $last) / $middleCount;
        $widths = [$first];

        for ($index = 0; $index < $middleCount; $index++) {
            $widths[] = $middleWidth;
        }

        $widths[] = $last;

        return $widths;
    }

    private function clean($value) {
        return iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', (string) $value);
    }

    private function lineCount($width, $text) {
        $words = preg_split('/\s+/', trim($text));
        $lines = 1;
        $current = '';
        foreach ($words as $word) {
            $candidate = $current === '' ? $word : $current . ' ' . $word;
            if ($this->GetStringWidth($candidate) > $width - 2) {
                $lines++;
                $current = $word;
            } else {
                $current = $candidate;
            }
        }
        return $lines;
    }
}
